In [2]:
import pandas as pd

In [3]:
df=pd.read_parquet("C:\\PEPE_TERRITORIAL\\data\\gst.parquet")

In [4]:
df_ipc=pd.read_excel("C:\\PEPE_TERRITORIAL\\data\\IPC_2021_2025_DEF.xlsx")

In [5]:
df

,Año Vigencia,Tipo de Entidad,Departamento,Código DANE,Sección Presupuestal,col_2,col_3,col_4,col_5,col_6,Apropiación Inicial,Apropiación Definitiva
0,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,73975867957,87750157245
1,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICION DE ACTIVOS NO FINANCIEROS,ACTIVOS FIJOS,MAQUINARIA Y EQUIPO,439998000,399998000
2,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,COMERCIO Y DISTRIBUCION; ALOJAMIENTO; SERVICIO...,229935424,113578567
3,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,SERVICIOS FINANCIEROS Y SERVICIOS CONEXOS; SER...,391350000,389475030
4,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,"SERVICIOS PARA LA COMUNIDAD, SOCIALES Y PERSON...",2370160726,4016719676
...,...,...,...,...,...,...,...,...,...,...,...,...
328111,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,CONTRIBUCIONES INHERENTES A LA NOMINA,APORTES DE CESANTIAS,19498904,19498904
328112,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,CONTRIBUCIONES INHERENTES A LA NOMINA,APORTES GENERALES AL SISTEMA DE RIESGOS LABORALES,1136006,1836006
328113,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,FACTORES CONSTITUTIVOS DE SALARIO,FACTORES SALARIALES COMUNES,177457092,177457092
328114,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,REMUNERACIONES NO CONSTITUTIVAS DE FACTOR SALA...,PRESTACIONES SOCIALES,9321551,9321551
328115,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,TRANSFERENCIAS CORRIENTES,A ORGANIZACIONES NACIONALES,A OTRAS ORGANIZACIONES NACIONALES,MEMBRESIAS,3500000,3500000

In [6]:
df_ipc = df_ipc.rename(columns={"Año": "Año Vigencia"})

In [7]:
df = df.merge(
    df_ipc[["Año Vigencia", "IPC"]],
    on="Año Vigencia",
    how="left"
)

In [8]:
df

,Año Vigencia,Tipo de Entidad,Departamento,Código DANE,Sección Presupuestal,col_2,col_3,col_4,col_5,col_6,Apropiación Inicial,Apropiación Definitiva,IPC
0,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,73975867957,87750157245,0.827675
1,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICION DE ACTIVOS NO FINANCIEROS,ACTIVOS FIJOS,MAQUINARIA Y EQUIPO,439998000,399998000,0.827675
2,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,COMERCIO Y DISTRIBUCION; ALOJAMIENTO; SERVICIO...,229935424,113578567,0.827675
3,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,SERVICIOS FINANCIEROS Y SERVICIOS CONEXOS; SER...,391350000,389475030,0.827675
4,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,"SERVICIOS PARA LA COMUNIDAD, SOCIALES Y PERSON...",2370160726,4016719676,0.827675
...,...,...,...,...,...,...,...,...,...,...,...,...,...
328111,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,CONTRIBUCIONES INHERENTES A LA NOMINA,APORTES DE CESANTIAS,19498904,19498904,0.904446
328112,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,CONTRIBUCIONES INHERENTES A LA NOMINA,APORTES GENERALES AL SISTEMA DE RIESGOS LABORALES,1136006,1836006,0.904446
328113,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,FACTORES CONSTITUTIVOS DE SALARIO,FACTORES SALARIALES COMUNES,177457092,177457092,0.904446
328114,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,REMUNERACIONES NO CONSTITUTIVAS DE FACTOR SALA...,PRESTACIONES SOCIALES,9321551,9321551,0.904446
328115,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,TRANSFERENCIAS CORRIENTES,A ORGANIZACIONES NACIONALES,A OTRAS ORGANIZACIONES NACIONALES,MEMBRESIAS,3500000,3500000,0.904446

In [9]:
print(df.isnull().sum())

Año Vigencia              0
Tipo de Entidad           0
Departamento              0
Código DANE               0
Sección Presupuestal      0
col_2                     0
col_3                     0
col_4                     0
col_5                     0
col_6                     0
Apropiación Inicial       0
Apropiación Definitiva    0
IPC                       0
dtype: int64

In [10]:
duplicados = df.duplicated().sum()

print("Número de filas duplicadas:", duplicados)

Número de filas duplicadas: 0

In [11]:
df.columns = df.columns.str.strip()

In [12]:
## Deflactar Apropiación Inicial
df["Apropiación_Inicial_real"] = (
    df["Apropiación Inicial"] / df["IPC"]
)

## Deflactar Apropiación Definitiva
df["Apropiación_Definitiva_real"] = (
    df["Apropiación Definitiva"] / df["IPC"]
)

In [13]:
df

,Año Vigencia,Tipo de Entidad,Departamento,Código DANE,Sección Presupuestal,col_2,col_3,col_4,col_5,col_6,Apropiación Inicial,Apropiación Definitiva,IPC,Apropiación_Inicial_real,Apropiación_Definitiva_real
0,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,73975867957,87750157245,0.827675,8.937797e+10,1.060201e+11
1,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICION DE ACTIVOS NO FINANCIEROS,ACTIVOS FIJOS,MAQUINARIA Y EQUIPO,439998000,399998000,0.827675,5.316075e+08,4.832793e+08
2,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,COMERCIO Y DISTRIBUCION; ALOJAMIENTO; SERVICIO...,229935424,113578567,0.827675,2.778090e+08,1.372261e+08
3,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,SERVICIOS FINANCIEROS Y SERVICIOS CONEXOS; SER...,391350000,389475030,0.827675,4.728308e+08,4.705654e+08
4,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,"SERVICIOS PARA LA COMUNIDAD, SOCIALES Y PERSON...",2370160726,4016719676,0.827675,2.863639e+09,4.853018e+09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328111,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,CONTRIBUCIONES INHERENTES A LA NOMINA,APORTES DE CESANTIAS,19498904,19498904,0.904446,2.155895e+07,2.155895e+07
328112,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,CONTRIBUCIONES INHERENTES A LA NOMINA,APORTES GENERALES AL SISTEMA DE RIESGOS LABORALES,1136006,1836006,0.904446,1.256024e+06,2.029978e+06
328113,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,FACTORES CONSTITUTIVOS DE SALARIO,FACTORES SALARIALES COMUNES,177457092,177457092,0.904446,1.962053e+08,1.962053e+08
328114,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,REMUNERACIONES NO CONSTITUTIVAS DE FACTOR SALA...,PRESTACIONES SOCIALES,9321551,9321551,0.904446,1.030636e+07,1.030636e+07
328115,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,TRANSFERENCIAS CORRIENTES,A ORGANIZACIONES NACIONALES,A OTRAS ORGANIZACIONES NACIONALES,MEMBRESIAS,3500000,3500000,0.904446,3.869772e+06,3.869772e+06

In [14]:
sorted(df["col_2"].dropna().unique())

['CONSOLIDACION',
 'FUNCIONAMIENTO',
 'INVERSION',
 'SERVICIO DE LA DEUDA PUBLICA']

In [15]:
###################################################################################################################################

In [16]:
df.loc[
    df["Tipo de Entidad"] == "Municipio",
    "Departamento"
].dropna().unique()

array(['Amazonas', 'Antioquia', 'Arauca', 'Archipiélago de San Andrés',
       'Atlántico', 'Bogotá D.C.', 'Bolívar', 'Boyacá', 'Caldas',
       'Caquetá', 'Casanare', 'Cauca', 'Cesar', 'Chocó', 'Cundinamarca',
       'Córdoba', 'Guainía', 'Guaviare', 'Huila', 'La Guajira',
       'Magdalena', 'Meta', 'Nariño', 'Norte de Santander', 'Putumayo',
       'Quindío', 'Risaralda', 'Santander', 'Sucre', 'Tolima',
       'Valle del Cauca', 'Vaupés', 'Vichada'], dtype=object)

In [17]:
dane = pd.read_excel("C:\\PEPE_TERRITORIAL\\data\\mun.xlsx")

In [18]:
print(dane.columns.tolist())

['Código', 'Nombre', ' Código ', ' Nombre ', 'Municipio\nIsla\nÁrea no municipalizada']

In [19]:
dane = dane.rename(columns={
    "Código": "Codigo_Dep",
    "Nombre": "Nombre_Dep",
    "Código.1": "Codigo_Mun",
    "Nombre.1": "Nombre_Mun",
    "Municipio\nIsla\nÁrea no municipalizada": "Tipo_DANE"
})

In [20]:
dane = dane.rename(columns={
    " Código ": "Codigo_Mun",
    " Nombre ": "Nombre_Mun"
})

In [21]:
print(dane.columns.tolist())

['Codigo_Dep', 'Nombre_Dep', 'Codigo_Mun', 'Nombre_Mun', 'Tipo_DANE']

In [22]:
dane["Codigo_Mun"] = (
    dane["Codigo_Mun"]
    .astype(str)
    .str.zfill(5)
)

df["Código DANE"] = (
    df["Código DANE"]
    .astype(str)
    .str.zfill(5)
)

In [23]:
dane[["Codigo_Mun", "Nombre_Mun"]].head()

  Codigo_Mun  Nombre_Mun
0      05001    MEDELLÍN
1      05002   ABEJORRAL
2      05004    ABRIAQUÍ
3      05021  ALEJANDRÍA
4      05030       AMAGÁ

In [24]:
df = df.merge(
    dane[["Codigo_Mun", "Nombre_Mun"]],
    left_on="Código DANE",
    right_on="Codigo_Mun",
    how="left"
)

In [25]:
## Ver nulos
print(df["Nombre_Mun"].isna().sum())

## Ver filas con nulos
df[df["Nombre_Mun"].isna()][
    ["Código DANE", "Departamento", "Tipo de Entidad"]
].drop_duplicates().head(20)

15857

     Código DANE  Departamento Tipo de Entidad
0          91000      Amazonas    Departamento
121        05000     Antioquia    Departamento
267        81000        Arauca    Departamento
385        08000     Atlántico    Departamento
522        13000       Bolívar    Departamento
663        15000        Boyacá    Departamento
800        17000        Caldas    Departamento
959        18000       Caquetá    Departamento
1095       85000      Casanare    Departamento
1209       19000         Cauca    Departamento
1372       20000         Cesar    Departamento
1502       27000         Chocó    Departamento
1615       25000  Cundinamarca    Departamento
1746       23000       Córdoba    Departamento
1884       94000       Guainía    Departamento
2005       95000      Guaviare    Departamento
2156       41000         Huila    Departamento
2285       44000    La Guajira    Departamento
2366       47000     Magdalena    Departamento
2483       50000          Meta    Departamento

In [26]:
df[df["Nombre_Mun"].isna()][
    ["Código DANE", "Tipo de Entidad", "Departamento"]
].drop_duplicates().head(50)

      Código DANE Tipo de Entidad                Departamento
0           91000    Departamento                    Amazonas
121         05000    Departamento                   Antioquia
267         81000    Departamento                      Arauca
385         08000    Departamento                   Atlántico
522         13000    Departamento                     Bolívar
663         15000    Departamento                      Boyacá
800         17000    Departamento                      Caldas
959         18000    Departamento                     Caquetá
1095        85000    Departamento                    Casanare
1209        19000    Departamento                       Cauca
1372        20000    Departamento                       Cesar
1502        27000    Departamento                       Chocó
1615        25000    Departamento                Cundinamarca
1746        23000    Departamento                     Córdoba
1884        94000    Departamento                     Guainía
2005        95000    Departamento                    Guaviare
2156        41000    Departamento                       Huila
2285        44000    Departamento                  La Guajira
2366        47000    Departamento                   Magdalena
2483        50000    Departamento                        Meta
2644        52000    Departamento                      Nariño
2783        54000    Departamento          Norte de Santander
2929        86000    Departamento                    Putumayo
3078        63000    Departamento                     Quindío
3157        66000    Departamento                   Risaralda
3269        68000    Departamento                   Santander
3418        70000    Departamento                       Sucre
3523        73000    Departamento                      Tolima
3652        76000    Departamento             Valle del Cauca
3823        97000    Departamento                      Vaupés
3891        99000    Departamento                     Vichada
81423       88000    Departamento  Archipiélago de San Andrés

In [27]:
df["Nombre_Mun"] = df["Nombre_Mun"].fillna(df["Departamento"])

In [28]:
df.isna().sum()

Año Vigencia                       0
Tipo de Entidad                    0
Departamento                       0
Código DANE                        0
Sección Presupuestal               0
col_2                              0
col_3                              0
col_4                              0
col_5                              0
col_6                              0
Apropiación Inicial                0
Apropiación Definitiva             0
IPC                                0
Apropiación_Inicial_real           0
Apropiación_Definitiva_real        0
Codigo_Mun                     15857
Nombre_Mun                         0
dtype: int64

In [37]:
columnas_borrar = [
    "codigo_depto",
    "Departamento_padre",
    "Código DANE_str",
    "Codigo_Mun"
]

df = df.drop(
    columns=[col for col in columnas_borrar if col in df.columns])

In [38]:
df.isna().sum()

Año Vigencia                   0
Tipo de Entidad                0
Departamento                   0
Código DANE                    0
Sección Presupuestal           0
col_2                          0
col_3                          0
col_4                          0
col_5                          0
col_6                          0
Apropiación Inicial            0
Apropiación Definitiva         0
IPC                            0
Apropiación_Inicial_real       0
Apropiación_Definitiva_real    0
Nombre_Mun                     0
dtype: int64

In [39]:
df.duplicated().sum()

np.int64(0)

In [40]:
df

,Año Vigencia,Tipo de Entidad,Departamento,Código DANE,Sección Presupuestal,col_2,col_3,col_4,col_5,col_6,Apropiación Inicial,Apropiación Definitiva,IPC,Apropiación_Inicial_real,Apropiación_Definitiva_real,Nombre_Mun
0,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,73975867957,87750157245,0.827675,8.937797e+10,1.060201e+11,Amazonas
1,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICION DE ACTIVOS NO FINANCIEROS,ACTIVOS FIJOS,MAQUINARIA Y EQUIPO,439998000,399998000,0.827675,5.316075e+08,4.832793e+08,Amazonas
2,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,COMERCIO Y DISTRIBUCION; ALOJAMIENTO; SERVICIO...,229935424,113578567,0.827675,2.778090e+08,1.372261e+08,Amazonas
3,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,SERVICIOS FINANCIEROS Y SERVICIOS CONEXOS; SER...,391350000,389475030,0.827675,4.728308e+08,4.705654e+08,Amazonas
4,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,"SERVICIOS PARA LA COMUNIDAD, SOCIALES Y PERSON...",2370160726,4016719676,0.827675,2.863639e+09,4.853018e+09,Amazonas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328111,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,CONTRIBUCIONES INHERENTES A LA NOMINA,APORTES DE CESANTIAS,19498904,19498904,0.904446,2.155895e+07,2.155895e+07,CUMARIBO
328112,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,CONTRIBUCIONES INHERENTES A LA NOMINA,APORTES GENERALES AL SISTEMA DE RIESGOS LABORALES,1136006,1836006,0.904446,1.256024e+06,2.029978e+06,CUMARIBO
328113,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,FACTORES CONSTITUTIVOS DE SALARIO,FACTORES SALARIALES COMUNES,177457092,177457092,0.904446,1.962053e+08,1.962053e+08,CUMARIBO
328114,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,REMUNERACIONES NO CONSTITUTIVAS DE FACTOR SALA...,PRESTACIONES SOCIALES,9321551,9321551,0.904446,1.030636e+07,1.030636e+07,CUMARIBO
328115,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,TRANSFERENCIAS CORRIENTES,A ORGANIZACIONES NACIONALES,A OTRAS ORGANIZACIONES NACIONALES,MEMBRESIAS,3500000,3500000,0.904446,3.869772e+06,3.869772e+06,CUMARIBO

In [41]:
df["Nombre_Mun"] = df["Nombre_Mun"].str.title().str.strip()

In [42]:
df

,Año Vigencia,Tipo de Entidad,Departamento,Código DANE,Sección Presupuestal,col_2,col_3,col_4,col_5,col_6,Apropiación Inicial,Apropiación Definitiva,IPC,Apropiación_Inicial_real,Apropiación_Definitiva_real,Nombre_Mun
0,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,CONSOLIDACION,73975867957,87750157245,0.827675,8.937797e+10,1.060201e+11,Amazonas
1,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICION DE ACTIVOS NO FINANCIEROS,ACTIVOS FIJOS,MAQUINARIA Y EQUIPO,439998000,399998000,0.827675,5.316075e+08,4.832793e+08,Amazonas
2,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,COMERCIO Y DISTRIBUCION; ALOJAMIENTO; SERVICIO...,229935424,113578567,0.827675,2.778090e+08,1.372261e+08,Amazonas
3,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,SERVICIOS FINANCIEROS Y SERVICIOS CONEXOS; SER...,391350000,389475030,0.827675,4.728308e+08,4.705654e+08,Amazonas
4,2022,Departamento,Amazonas,91000,ENTIDADES TERRITORIALES - ADMINISTRACION CENTRAL,FUNCIONAMIENTO,ADQUISICION DE BIENES Y SERVICIOS,ADQUISICIONES DIFERENTES DE ACTIVOS,ADQUISICION DE SERVICIOS,"SERVICIOS PARA LA COMUNIDAD, SOCIALES Y PERSON...",2370160726,4016719676,0.827675,2.863639e+09,4.853018e+09,Amazonas
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
328111,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,CONTRIBUCIONES INHERENTES A LA NOMINA,APORTES DE CESANTIAS,19498904,19498904,0.904446,2.155895e+07,2.155895e+07,Cumaribo
328112,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,CONTRIBUCIONES INHERENTES A LA NOMINA,APORTES GENERALES AL SISTEMA DE RIESGOS LABORALES,1136006,1836006,0.904446,1.256024e+06,2.029978e+06,Cumaribo
328113,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,FACTORES CONSTITUTIVOS DE SALARIO,FACTORES SALARIALES COMUNES,177457092,177457092,0.904446,1.962053e+08,1.962053e+08,Cumaribo
328114,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,GASTOS DE PERSONAL,PLANTA DE PERSONAL PERMANENTE,REMUNERACIONES NO CONSTITUTIVAS DE FACTOR SALA...,PRESTACIONES SOCIALES,9321551,9321551,0.904446,1.030636e+07,1.030636e+07,Cumaribo
328115,2023,Municipio,Vichada,99773,ENTIDADES TERRITORIALES - SECCION PRESUPUESTAL...,FUNCIONAMIENTO,TRANSFERENCIAS CORRIENTES,A ORGANIZACIONES NACIONALES,A OTRAS ORGANIZACIONES NACIONALES,MEMBRESIAS,3500000,3500000,0.904446,3.869772e+06,3.869772e+06,Cumaribo

In [ ]:
################################################################################################################################################

In [43]:
df.to_parquet(
    "C:\\PEPE_TERRITORIAL\\data\\gastos_deflactado_mun.parquet",
    index=False
)